
# Generated by Django 5.0.6 on 2024-07-10 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название статуса:')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'db_table': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название типа:')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'db_table': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.basemodel')),
                ('summary', models.CharField(max_length=50, verbose_name='Краткое Описание')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Подробное описание')),
                ('statuses', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='webapp.status')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='webapp.type')),
            ],
            options={
                'verbose_name': 'Трекер задач',
                'verbose_name_plural': 'Трекеры задач',
                'db_table': 'Issues',
            },
            bases=('webapp.basemodel',),
        ),
    ]
