# Generated by Django 5.0.6 on 2024-07-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, default='Пустой', max_length=500, null=True, verbose_name='Подробное описание'),
        ),
    ]
