
# Generated by Django 5.0.6 on 2024-07-11 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_issue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='statuses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='webapp.status', verbose_name='Статусы'),
        ),
        migrations.RemoveField(
            model_name='issue',
            name='types',
        ),
        migrations.AddField(
            model_name='issue',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='issues', to='webapp.type', verbose_name='Типы'),
        ),
    ]
