# Generated by Django 5.0.6 on 2024-07-17 13:04

from django.db import migrations


def transfer_project(apps, schema_editor):
    Project = apps.get_model('webapp', 'Project')
    Issue = apps.get_model('webapp', 'Issue')

    projects = Project.objects.create(title='Проект1', start_date='2024-07-17')

    Issue.objects.filter(project__isnull=True).update(project=projects)


class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0004_project_issue_project'),
    ]

    operations = [
        migrations.RunPython(transfer_project)
    ]
