# Generated by Django 5.0.6 on 2024-07-17 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20240717_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='webapp.project', verbose_name='Проект'),
            preserve_default=False,
        ),
    ]
